# Task 11: Download Roles From an Ansible Galaxy and Use Them
# Use Ansible Galaxy to download and install geerlingguy.haproxy role in /home/automation/plays/roles.# 

# Create a playbook /home/automation/plays/haproxy.yml that runs on servers in the proxy host group and does the following:# 

# Use geerlingguy.haproxy role to load balance request between hosts in the webservers host group.
# Use roundrobin load balancing method.
# HAProxy backend servers should be configured for HTTP only (port 80).
# Firewall is configured to allow all incoming traffic on port TCP 80.
# If your playbook works, then doing “curl http://ansible2.hl.local/” should return output from the web server (see task #10).
# Running the command again should return output from the other web server.
#
---
- hosts: proxy
  gather_facts: true 
  become: true
  tasks: 
    - name: Ensure Firewalld is installed 
      yum: name=firewalld state=present

    - name: Ensure firewalld is runiing 
      service: name=firewalld state=started enabled=true

    - name: Allowing http request 
      firewalld:
         port: 80/tcp 
         state: enabled
         permanent: true
         immediate: true
    
  roles:
    - { role: geerlingguy.haproxy }
...

# [automation@ansmaster Ansible Plays Roles Practice on 2.9]$ ansible-playbook haproxy.yml # 

# PLAY [proxy] *****************************************************************************************************************************************# 

# TASK [Gathering Facts] *******************************************************************************************************************************
# ok: [ansnode_1]# 

# TASK [geerlingguy.haproxy : Ensure HAProxy is installed.] ********************************************************************************************
# ok: [ansnode_1]# 

# TASK [geerlingguy.haproxy : Ensure HAProxy is enabled (so init script will start it on Debian).] *****************************************************
# skipping: [ansnode_1]# 

# TASK [geerlingguy.haproxy : Get HAProxy version.] ****************************************************************************************************
# ok: [ansnode_1]# 

# TASK [geerlingguy.haproxy : Set HAProxy version.] ****************************************************************************************************
# ok: [ansnode_1]# 

# TASK [geerlingguy.haproxy : Copy HAProxy configuration in place.] ************************************************************************************
# ok: [ansnode_1]# 

# TASK [geerlingguy.haproxy : Ensure HAProxy is started and enabled on boot.] **************************************************************************
# ok: [ansnode_1]# 

# TASK [Ensure Firewalld is installed] *****************************************************************************************************************
# ok: [ansnode_1]# 

# TASK [Ensure firewalld is runiing] *******************************************************************************************************************
# ok: [ansnode_1]# 

# TASK [Allowing http request] *************************************************************************************************************************
# ok: [ansnode_1]# 

# PLAY RECAP *******************************************************************************************************************************************
# ansnode_1                  : ok=9    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   # 

# Playbook run took 0 days, 0 hours, 0 minutes, 8 seconds
